version: '3.4'
services:
  db:
    image: scalable-system-for-occurrence-analysis-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: spring_rest_occurrence_analysis
    ports:
      - "3308:3306"
    networks:
      - b2w-network
  spring-rest-occurrence-analysis:
    image: scalable-system-for-occurrence-analysis-app
    restart: always
    build: ./scalable-system-for-occurrence-analysis-container
    working_dir: /scalable-system-for-occurrence-analysis-container
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./scalable-system-for-occurrence-analysis-container:/scalable-system-for-occurrence-analysis-container
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - b2w-network
networks:
    b2w-network:
        driver: bridge